import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Pixelify_Sans } from "next/font/google";
import "./globals.css";
import { DirectoryProvider } from "./directoryContext";
import React from "react";
import OpenedWindowsProvider from "@/app/context/openedWindowsContext";
import SpeechRecognitionProvider from "@/app/context/speechRecognitionContext";
import SchedulerProvider from "./context/schedulerContext";
import MemoryManagerProvider from "./context/memoryManagerContext";
import CameraProvider from "./context/cameraContext";
import { NoteProvider } from "./context/noteContext";

const inter = Inter({ subsets: ["latin"] });
const pixelifySans = Pixelify_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-hidden">
      <body className={`${pixelifySans.className} bg-primary`}>
        {/*<SpeechRecognitionProvider>*/}
        <OpenedWindowsProvider>
          <DirectoryProvider>
            <SchedulerProvider>
              <MemoryManagerProvider>
                <CameraProvider>
                  <NoteProvider windowIndex={1}>{children}</NoteProvider>
                </CameraProvider>
              </MemoryManagerProvider>
            </SchedulerProvider>
          </DirectoryProvider>
        </OpenedWindowsProvider>
        {/*</SpeechRecognitionProvider>*/}
      </body>
    </html>
  );
}
