import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DirectoryProvider } from "./directoryContext";
import React from "react";
import OpenedWindowsProvider from "@/app/context/openedWindowsContext";
import SpeechRecognitionProvider from "@/app/context/speechRecognitionContext";
import SchedulerProvider from "./context/schedulerContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-hidden">
      <body className={`${inter.className} bg-primary`}>
      {/*<SpeechRecognitionProvider>*/}
      <OpenedWindowsProvider>
        <DirectoryProvider>
          <SchedulerProvider>
            {children}
          </SchedulerProvider>
        </DirectoryProvider>
      </OpenedWindowsProvider>
      {/*</SpeechRecognitionProvider>*/}
      </body>
    </html>
  );
}
